P2 201 fe payroll history
LangaraVoyagers/project-2 pull request #20
Opened 2024-03-02 20:48 UTC by ALFAROSO

https://team-voyagers.atlassian.net/jira/software/projects/P2/boards/2?assignee=712020%3Aa4d78f0d-920a-427a-a5ce-b36979797950&selectedIssue=P2-201

2024-03-02 20:53 UTC, ReinhardtBotha approved these changes
💵

2024-03-04 18:22 UTC, whamester requested changes

2024-03-04 18:22 UTC, whamester commented on src/pages/Payroll/Payroll.tsx
> +  const CustomPayroll = () => {
rename component to Payroll

file name and component name must be the same

2024-03-04 18:22 UTC, whamester commented on src/pages/Payroll/Payroll.tsx
> +  const columns : GridColDef[] = [
move the columns out of the component

2024-03-04 18:22 UTC, whamester commented on src/pages/Payroll/Payroll.tsx
> +  const formatDate = (timestamp : number) => {
note: refactor this format date to use intl messages

2024-03-04 21:53 UTC, whamester approved these changes

2024-03-04 21:54 UTC, whamester commented
Pending: format date with intl

2024-03-04 22:27 UTC, BryanCaldeira approved these changes

2024-03-04 22:29 UTC, merged